### ISSUE TITLE
Missing maven dependency on remote repository (http://52north.org/maven/)

### ISSUE THREAD

**Issue by ggcaponetto** [conterra/mapapps-remote-project-blueprint#1]
Hello,
I am currently unable to build this project because a dependency is missing in the remote repository [http://52north.org/maven/](url).

The steps to reproduce this issue are:

1.  Fresh installation of Map.apps 4.2.2 and "mapapps-remote-project-blueprint" app
2.  `jetty:run`

The error I get is the following:
`
[ERROR] Non-resolvable import POM: Failure to find de.conterra.jsregistry:ct-jsregistry:pom:1.1.3 in http://52north.org/maven/repo/releases was cached in the local repository, resolution will not be reattempted until the update interval of 52n-dependencies has elapsed or updates are forced @ de.conterra.jsrt:ct-jsrt-test:1.1.2, C:\Users\Giuseppe\.m2\repository\de\conterra\jsrt\ct-jsrt-test\1.1.2\ct-jsrt-test-1.1.2.pom, line 18, column 25
`

Things I tried:

- Force updates via maven

**Comment by julkuh** [comment]
Hello Guiseppe,

we've updated the mapapps rollout so you could simply download it again from the [Downloadportal](https://downloads.conterra.de/en/downloads).

Happy coding :)
Julian

**Comment by ggcaponetto** [comment]
Solved installing the new sources. Thanks @julkuh
