### ISSUE TITLE
CORS settings + Jetty

### ISSUE THREAD

**Issue by ggcaponetto** [conterra/mapapps-remote-project-blueprint#2]
Hello Conterra Dev Team,

I'd like to know where it is possible to define the settings to allow CORS with `jetty:run -P env-dev`.

Cheers, Giuseppe.

**Comment by julkuh** [comment]
Hello Giuseppe,

1. Step
you can create a custom 'mapapps_dev.properties' e.g. in Folder '%userprofile%'.
Put your configuration the properties you want e.g.

`cors.any.origins=true`

Please refer to the [docs ](https://developernetwork.conterra.de/en/documentation/mapapps/42/administration-guide/base-configuration) for furtehr info about the properties.

2. Step
Use the created .properties file during mvn jetty:run by including it to the run command:
`jetty:run -Penv-dev -Dlocal.configfile=C:\Users\USERNAME\mapapps_dev.properties/`


regards,
Julain

**Comment by ggcaponetto** [comment]
Thank you very much.
